name: aplicacion_para_diabeticos
description: Aplicación de hábitos para personas con diabetes
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  timezone: ^0.9.4
  flutter_native_timezone: ^2.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
